
intrebari = ("Câte elemente sunt în tabelul periodic al elementelor - de la Hidrogen la Organesson?: ",
             "Ce reprezintă raza unui cerc?: ",
             "Ce este refracția luminii?: ",
             "Care dintre următoarele fenomene nu poate fi explicat prin teoria cuantică?: ",
             "Ce este cuantizarea sarcinii electrice?: ",
             "Care dintre următoarele este un limbaj de programare de nivel înalt?: ",
             "Care este principala funcție a unui compilator?: ",
             "Ce este o adresă IP?: ",
             "Ce este virtualizarea?: ",
             "Care este rezultatul ecuației integrate -> ∫(2x^3 - 3x^2 + 4x - 1)dx?: ",
             "Care dintre următoarele paradigme de programare se concentrează pe separarea datelor și a codului?: ",
             "Ce este programarea funcțională?: ",
             "Care este valoarea lui √(cos²(45°) + sin²(45°))?: ",
             "Teorema lui Pitagora afirmă că într-un triunghi dreptunghic, pătratul lungimii ipotenuzei este egal cu suma pătratelor lungimilor celor două catete. Dacă lungimile catetelor unui triunghi dreptunghic sunt 3 cm și 4 cm, care este lungimea ipotenuzei?: ",
             "O undă sonoră se propagă într-un mediu solid, iar frecvența sa este de 500 Hz. Dacă unda trece într-un alt mediu solid în care viteza sunetului este dublă față de cea inițială, care va fi noua frecvență?: ",
             "O particulă de masă m și sarcină electrică q se mișcă într-un câmp magnetic cu o viteză v. Forța magnetică asupra particulei este proporțională cu cine?: ",
             "Care dintre următoarele afirmații este adevărată despre energia cinetică?: ",
             "Care este rolul protocolului TCP (Transmission Control Protocol) într-o rețea de calculatoare?")

options = (("A. 117",
            "B. 115",
            "C. 119",
            "D. 118"),
           ("A. Jumătate din circumferința cercului",
            "B. Distanța de la centru la orice punct de pe cerc",
            "C. Diametrul cercului",
            "D. Lungimea unui segment care unește centrul cu orice punct de pe circumferință"),
           ("A. Răspândirea luminii atunci când trece printr-un mediu transparent",
            "B. Schimbarea direcției luminii atunci când trece dintr-un mediu în altul",
            "C. Absorbția luminii de către un mediu opac",
            "D. Creșterea vitezei luminii într-un mediu dens"),
           ("A. Efectul fotoelectric",
            "B. Dispersia luminii",
            "C. Interferența undelor luminoase",
            "D. Polarizarea luminii"),
           ("A. Faptul că sarcina electrică este întotdeauna un număr întreg de unități elementare de sarcină",
            "B. Faptul că sarcina electrică poate fi orice valoare continuă",
            "C. Faptul că sarcina electrică este divizibilă în părți mici și nedivizibile",
            "D. Faptul că sarcina electrică este proporțională cu voltajul aplicat"),
           ("A. Assembly",
            "B. C++",
            "C. C#",
            "D. Mașină"),
           ("A. Transformarea codului sursă în cod mașină executabil",
            "B. Executarea programelor și gestionarea resurselor de sistem",
            "C. Editarea și formatarea codului sursă pentru a-l face mai ușor de citit",
            "D. Gestionarea bazei de date și efectuarea operațiilor de interogare"),
           ("A. Un limbaj de programare pentru dezvoltarea aplicațiilor web",
            "B. Un set de instrucțiuni pentru rezolvarea unei probleme",
            "C. Un algoritm de criptare a datelor într-un mesaj",
            "D. Un identificator unic atribuit unui dispozitiv într-o rețea de calculatoare"),
           ("A. Un algoritm de transformare a datelor într-un format standard",
            "B. Un limbaj de programare utilizat pentru dezvoltarea aplicațiilor desktop",
            "C. Un sistem de operare care permite rularea mai multor sisteme de operare pe același calculator",
            "D. Un protocol de rețea pentru transferul de fișiere între dispozitive"),
           ("A. x^4 - x^3 + 2x^2 - x + C",
            "B. (1/2)x^4 - (1/3)x^3 + 2x^2 - x + C",
            "C. (1/2)x^4 - x^3 + 2x^2 - x + C",
            "D. (1/2)x^4 - (1/3)x^3 + 2x^2 - x^2 + C"),
           ("A. Programarea funcțională",
            "B. Programarea orientată pe obiecte",
            "C. Programarea procedurală",
            "D. Programarea generică"),
           ("A. Un algoritm de sortare a datelor în ordine aleatoare",
            "B. Un limbaj de programare pentru dezvoltarea jocurilor video",
            "C. Un mod de gestionare a memoriei într-un sistem de operare",
            "D. Un stil de programare în care se folosesc funcții ca elemente fundamentale de construcție a programelor"),
           ("A. 1",
            "B. √2/2",
            "C. √3/2",
            "D. 1/2"),
           ("A. 3 cm",
            "B. 6 cm",
            "C. 5 cm",
            "D. 8 cm"),
           ("A. 500 Hz",
            "B. 250 Hz",
            "C. 1000 Hz",
            "D. 750 Hz"),
           ("A. m",
            "B. q",
            "C. v",
            "D. m, q și v"),
           ("A. Este definită ca măsura rezistenței unui obiect la schimbarea stării sale de repaus sau de mișcare.",
            "B. Este definită ca energia unui obiect în funcție de poziția sa într-un câmp gravitațional.",
            "C. Este definită ca energia unui obiect în funcție de sarcina electrică pe care o poartă.",
            "D. Este definită ca energia unui obiect în funcție de mișcarea sa."),
           ("A. Asigură livrarea datelor în mod fiabil și în ordine corectă.",
            "B. Oferă o interfață de acces la internet prin cabluri de fibră optică.",
            "C. Gestionează adresele IP și se ocupă de rutarea pachetelor în rețea.",
            "D. Permite conexiuni rapide și sigure între servere și clienți."))