
questions = ("How many elements are in the periodic table of elements - from Hydrogen to Organesson?: ",
             "What is the radius of a circle?: ",
             "What is refraction of light?: ",
             "Which of the following phenomena cannot be explained by quantum theory?: ",
             "What is electric charge quantization?: ",
             "Which of the following is a high-level programming language?: ",
             "What is the main function of a compiler?: ",
             "What is an IP address?: ",
             "What is virtualization?: ",
             "What is the result of the integrated equation -> ∫(2x^3 - 3x^2 + 4x - 1)dx?: ",
             "Which of the following programming paradigms focuses on the separation of data and code?: ",
             "What is functional programming?: ",
             "What is the value of √(cos²(45°) + sin²(45°))?: ",
             "The Pythagorean theorem states that in a right triangle, the square of the length of the hypotenuse is equal to the sum of the squares of the lengths of the two legs. If the lengths of the legs of a right triangle are 3 cm and 4 cm, what is the length of the hypotenuse?: ",
             "A sound wave propagates in a solid medium and its frequency is 500 Hz. If the wave passes into another solid medium where the speed of sound is twice that of the original, what will be the new frequency?: ",
             "A particle of mass m and electric charge q moves in a magnetic field with a velocity v. The magnetic force on the particle is proportional to who?: ",
             "Which of the following statements is true about kinetic energy?: ",
             "What is the role of TCP (Transmission Control Protocol) in a computer network?")

options = (("A. 117",
            "B. 115",
            "C. 119",
            "D. 118"),
           ("A. Half the circumference of the circle",
            "B. The distance from the center to any point on the circle",
            "C. The diameter of the circle",
            "D. The length of a segment joining the center to any point on the circumference"),
           ("A. Scattering of light when passing through a transparent medium",
            "B. Changing the direction of light when it passes from one medium to another",
            "C. Absorption of light by an opaque medium",
            "D. Increasing the speed of light in a dense medium"),
           ("A. The photoelectric effect",
            "B. Light dispersion",
            "C. Interference of light waves",
            "D. Polarization of light"),
           ("A. The fact that electric charge is always an integer number of elementary units of charge",
            "B. The fact that the electric charge can be any continuous value",
            "C. The fact that electric charge is divisible into small and indivisible parts",
            "D. The fact that the electric charge is proportional to the applied voltage"),
           ("A. Assembly",
            "B. C++",
            "C. C#",
            "D. Machine"),
           ("A. Converting source code into executable machine code",
            "B. Running programs and managing system resources",
            "C. Editing and formatting the source code to make it easier to read",
            "D. Managing the database and performing query operations"),
           ("A. A programming language for developing web applications",
            "B. A set of instructions for solving a problem",
            "C. An algorithm for encrypting the data in a message",
            "D. A unique identifier assigned to a device on a computer network"),
           ("A. An algorithm for transforming data into a standard format",
            "B. A programming language used for developing desktop applications",
            "C. An operating system that allows multiple operating systems to run on the same computer",
            "D. A network protocol for transferring files between devices"),
           ("A. x^4 - x^3 + 2x^2 - x + C",
            "B. (1/2)x^4 - (1/3)x^3 + 2x^2 - x + C",
            "C. (1/2)x^4 - x^3 + 2x^2 - x + C",
            "D. (1/2)x^4 - (1/3)x^3 + 2x^2 - x^2 + C"),
           ("A. Functional programming",
            "B. Object Oriented Programming",
            "C. Procedural programming",
            "D. Generic programming"),
           ("A. An algorithm for sorting data into random order",
            "B. A programming language for video game development",
            "C. A way of managing memory in an operating system",
            "D. A programming style that uses functions as the fundamental building blocks of programs"),
           ("A. 1",
            "B. √2/2",
            "C. √3/2",
            "D. 1/2"),
           ("A. 3 cm",
            "B. 6 cm",
            "C. 5 cm",
            "D. 8 cm"),
           ("A. 500 Hz",
            "B. 250 Hz",
            "C. 1000 Hz",
            "D. 750 Hz"),
           ("A. m",
            "B. q",
            "C. v",
            "D. m, q and v"),
           ("A. It is defined as the measure of an object's resistance to changing its state of rest or motion",
            "B. It is defined as the energy of an object as a function of its position in a gravitational field",
            "C. It is defined as the energy of an object as a function of the electrical charge it carries",
            "D. It is defined as the energy of an object as a function of its motion"),
           ("A. Ensures data is delivered reliably and in the correct order",
            "B. Provides an Internet access interface through fiber optic cables",
            "C. It manages IP addresses and handles the routing of packets on the network",
            "D. It allows fast and secure connections between servers and clients"))
